name: 3PP License Check

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *' # Runs every day at 4am: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

jobs:

  License-check:
    name: 3PP License Check

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['18.x']
        java: ['11']

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - name: Use Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Run dash-licenses
        if: matrix.tests != 'skip'
        shell: bash
        run: |
          # build a local npm package "payload" and install it
          npm pack
          npm install
          npm install --no-save ./eclipse-dash-nodejs-wrapper-*.tgz 
          npx dash-licenses-wrapper --inputFile=package-lock.json
        env:
          DASH_LICENSES_PAT: ${{ secrets.DASH_LICENSES_PAT }}
